/**
 * tripConstants
 *
 * @package                TruckAdmin
 * @subpackage             Trip Constants
 * @category               Constants
 * @DateOfCreation         14 Aug 2018
 * @ShortDescription       This is responsible for Trip Constants action names
 */
export const tripConstants = {
    
    // Fetch Action Constants
    TRIP_FETCH_REQUEST     : 'TRIP_FETCH_REQUEST',
    TRIP_FETCH_SUCCESS     : 'TRIP_FETCH_SUCCESS',
    TRIP_FETCH_FAILURE     : 'TRIP_FETCH_FAILURE',
    
    // Add Action Constants
    TRIP_SAVE_REQUEST    : 'TRIP_SAVE_REQUEST',
    TRIP_SAVE_SUCCESS    : 'TRIP_SAVE_SUCCESS',
    TRIP_SAVE_FAILURE    : 'TRIP_SAVE_FAILURE',

    // Delete action constants
    TRIP_DELETE_REQUEST    : 'TRIP_DELETE_REQUEST',
    TRIP_DELETE_SUCCESS    : 'TRIP_DELETE_SUCCESS',
    TRIP_DELETE_FAILURE    : 'TRIP_DELETE_FAILURE',
    
    // Reset State
    TRIP_RESET_STATE     : 'TRIP_RESET_STATE',
    TRIP_UPDATE_STATE    : 'TRIP_UPDATE_STATE',

    // Map view
    MAP_FETCH_SUCCESS : 'MAP_FETCH_SUCCESS',
    MAP_FETCH_REQUEST : 'MAP_FETCH_REQUEST',
    MAP_FETCH_FAILURE : 'MAP_FETCH_FAILURE',

    // COMPLAINT view
    COMPLAINT_FETCH_SUCCESS : 'COMPLAINT_FETCH_SUCCESS',
    COMPLAINT_FETCH_REQUEST : 'COMPLAINT_FETCH_REQUEST',
    COMPLAINT_FETCH_FAILURE : 'COMPLAINT_FETCH_FAILURE',

    // LIABILITY view
    LIABILITY_FETCH_SUCCESS : 'LIABILITY_FETCH_SUCCESS',
    LIABILITY_FETCH_REQUEST : 'LIABILITY_FETCH_REQUEST',
    LIABILITY_FETCH_FAILURE : 'LIABILITY_FETCH_FAILURE',

    // LIABILITY Update view
    LIABILITY_UPDATE_SUCCESS : 'LIABILITY_UPDATE_SUCCESS',
    LIABILITY_UPDATE_REQUEST : 'LIABILITY_UPDATE_REQUEST',
    LIABILITY_UPDATE_FAILURE : 'LIABILITY_UPDATE_FAILURE',

    LIABILITY_RESET_STATE     : 'LIABILITY_RESET_STATE',
};
